//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxerMeToMyAnimeList.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("718ef986da4de4983f4cff4ce97ce364")]
        public string MAL_CLIENT_ID {
            get {
                return ((string)(this["MAL_CLIENT_ID"]));
            }
            set {
                this["MAL_CLIENT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dadae21cd84bef2bb87a07d2b1905fa437d164d4dea45045466312482d8720a1")]
        public string MAL_CLIENT_SECRET {
            get {
                return ((string)(this["MAL_CLIENT_SECRET"]));
            }
            set {
                this["MAL_CLIENT_SECRET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://proxer.me/user/80217/anime#top")]
        public string PROXER_ANIMELIST_URL {
            get {
                return ((string)(this["PROXER_ANIMELIST_URL"]));
            }
            set {
                this["PROXER_ANIMELIST_URL"] = value;
            }
        }
    }
}
